name: PostUpgradeTask Quarkus

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
      - 'main'

jobs:
  postupgradetask:
    if: ${{ startsWith(github.head_ref, 'renovate/quarkus') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.head_ref
        run: echo ${{ github.head_ref }}

      - name: Parse branch name
        id: parse
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          echo "DEPNAME=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f1)" >> "$GITHUB_OUTPUT"
          echo "CURR_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f2)" >> "$GITHUB_OUTPUT"
          echo "NEW_VERSION=$(echo $BRANCH | cut -d'/' -f2 | cut -d'_' -f3)" >> "$GITHUB_OUTPUT"

      - name: echo parsed values
        env:
          DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
          CURR_VERSION: ${{ steps.parse.outputs.CURR_VERSION }}
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: echo "depname=${DEPNAME}, currVersion=${CURR_VERSION}, newVersion=${NEW_VERSION}"

      - uses: actions/checkout@v4
        name: checkout
        with:
          ref: main

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Upgrade
        env:
          NEW_VERSION: ${{ steps.parse.outputs.NEW_VERSION }}
        run: |
          ls -al
          ./mvnw -v
          java --version
          ./mvnw -B io.quarkus.platform:quarkus-maven-plugin:${NEW_VERSION}:update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          title: Upgrade quarkus from ${{ steps.parse.outputs.CURR_VERSION }} to ${{ steps.parse.outputs.NEW_VERSION }}
          branch: postupgradetask/${{ steps.parse.outputs.DEPNAME }}_${{ steps.parse.outputs.CURR_VERSION }}_${{ steps.parse.outputs.NEW_VERSION }}
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body: |
            Upgrade quarkus version
